[I 18:28:24.925 NotebookApp] Serving notebooks from local directory: /home/ubuntu/Python-Notebook
[I 18:28:24.925 NotebookApp] Jupyter Notebook 6.5.3 is running at:
[I 18:28:24.925 NotebookApp] http://VM-12-9-ubuntu:8888/
[I 18:28:24.925 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:28:39.397 NotebookApp] 302 GET / (171.43.236.71) 0.450000ms
[W 18:30:22.568 NotebookApp] Forbidden
[W 18:30:22.568 NotebookApp] 403 GET /api/contents?type=directory&_=1679048919864 (180.101.244.11) 0.740000ms referer=http://114.132.78.107:8888/tree?
[W 18:30:41.641 NotebookApp] Notebook matplotlib/matplotlib.ipynb is not trusted
[I 18:30:45.717 NotebookApp] Kernel started: 47746fda-9cb3-4c94-9b05-98a7d44dc36b, name: python3
[I 18:31:24.574 NotebookApp] Starting buffering for 47746fda-9cb3-4c94-9b05-98a7d44dc36b:695ac1f9d462403b8eb6845b86e93f44
[I 18:32:30.442 NotebookApp] 302 GET / (171.43.236.71) 0.420000ms
[W 18:33:06.114 NotebookApp] Forbidden
[W 18:33:06.114 NotebookApp] 403 GET /api/contents?type=directory&_=1679048921378 (59.83.208.106) 0.710000ms referer=http://114.132.78.107:8888/tree?
[I 18:33:10.294 NotebookApp] 302 GET / (171.43.236.71) 0.400000ms
[I 18:33:10.320 NotebookApp] 302 GET /tree? (171.43.236.71) 0.630000ms
[W 18:33:55.351 NotebookApp] Forbidden
[W 18:33:55.351 NotebookApp] 403 GET /api/config/tree?_=1679048919859 (180.101.245.250) 0.710000ms referer=http://114.132.78.107:8888/tree?
[W 18:34:18.020 NotebookApp] Forbidden
[W 18:34:18.020 NotebookApp] 403 GET /api/terminals?_=1679048919863 (220.196.160.151) 0.690000ms referer=http://114.132.78.107:8888/tree?
[W 18:34:29.171 NotebookApp] Couldn't authenticate WebSocket connection
[W 18:34:29.176 NotebookApp] 403 GET /api/kernels/47746fda-9cb3-4c94-9b05-98a7d44dc36b/channels?session_id=695ac1f9d462403b8eb6845b86e93f44 (220.196.160.95) 5.680000ms referer=None
